CREATE TABLE budynek (
    id_budynku NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adres VARCHAR2(200) NOT NULL,
    liczba_pieter NUMBER NOT NULL,
    rok_budowy NUMBER(4),
    liczba_mieszkan NUMBER
);

CREATE TABLE mieszkanie (
    id_mieszkania NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_budynku NUMBER NOT NULL,
    numer VARCHAR2(20) NOT NULL,
    metraz NUMBER(10,2),
    liczba_pokoi NUMBER,
    CONSTRAINT fk_mieszkanie_budynek FOREIGN KEY (id_budynku) REFERENCES budynek(id_budynku)
);

CREATE TABLE czlonek (
    id_czlonka NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mieszkania NUMBER NOT NULL,
    imie VARCHAR2(100) NOT NULL,
    nazwisko VARCHAR2(100) NOT NULL,
    pesel VARCHAR2(11),
    telefon VARCHAR2(20),
    email VARCHAR2(100),
    data_przystapienia DATE DEFAULT SYSDATE,
    CONSTRAINT fk_czlonek_mieszkanie FOREIGN KEY (id_mieszkania) REFERENCES mieszkanie(id_mieszkania)
);

CREATE TABLE pracownik (
    id_pracownika NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imie VARCHAR2(100) NOT NULL,
    nazwisko VARCHAR2(100) NOT NULL,
    stanowisko VARCHAR2(100),
    telefon VARCHAR2(20),
    email VARCHAR2(100),
    data_zatrudnienia DATE DEFAULT SYSDATE
);

CREATE TABLE uslugi (
    id_uslugi NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa_uslugi VARCHAR2(200) NOT NULL,
    cena_za_jednostke NUMBER(10,2) NOT NULL,
    jednostka_miary VARCHAR2(50)
);

CREATE TABLE naprawa (
    id_naprawy NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mieszkania NUMBER NOT NULL,
    id_pracownika NUMBER,
    opis VARCHAR2(500),
    data_zgloszenia DATE DEFAULT SYSDATE,
    data_wykonania DATE,
    status VARCHAR2(50) DEFAULT 'zgloszona',
    CONSTRAINT fk_naprawa_mieszkanie FOREIGN KEY (id_mieszkania) REFERENCES mieszkanie(id_mieszkania),
    CONSTRAINT fk_naprawa_pracownik FOREIGN KEY (id_pracownika) REFERENCES pracownik(id_pracownika)
);

CREATE TABLE oplata (
    id_oplaty NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mieszkania NUMBER NOT NULL,
    id_uslugi NUMBER NOT NULL,
    kwota NUMBER(10,2) NOT NULL,
    data_naliczenia DATE DEFAULT SYSDATE,
    status_oplaty VARCHAR2(50) DEFAULT 'nieoplacone',
    zuzycie NUMBER(10,3),
    CONSTRAINT fk_oplata_mieszkanie FOREIGN KEY (id_mieszkania) REFERENCES mieszkanie(id_mieszkania),
    CONSTRAINT fk_oplata_uslugi FOREIGN KEY (id_uslugi) REFERENCES uslugi(id_uslugi)
);

CREATE TABLE uzytkownicy (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR2(100) NOT NULL UNIQUE,
    haslo VARCHAR2(255) NOT NULL
);

CREATE TABLE log_zmian_czlonka (
    id_logu NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_czlonka NUMBER,
    operacja VARCHAR2(50),
    stare_dane VARCHAR2(1000),
    nowe_dane VARCHAR2(1000),
    data_zmiany TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE PROCEDURE zwieksz_oplaty(p_procent IN NUMBER) AS
BEGIN
    UPDATE uslugi SET cena_za_jednostke = cena_za_jednostke * (1 + p_procent / 100);
    COMMIT;
END;
/

CREATE OR REPLACE FUNCTION dodaj_oplate_fn(
    p_id_mieszkania IN NUMBER,
    p_id_uslugi IN NUMBER,
    p_zuzycie IN NUMBER
) RETURN NUMBER AS
    v_cena NUMBER;
    v_kwota NUMBER;
BEGIN
    SELECT cena_za_jednostke INTO v_cena FROM uslugi WHERE id_uslugi = p_id_uslugi;
    v_kwota := v_cena * p_zuzycie;
    
    INSERT INTO oplata (id_mieszkania, id_uslugi, kwota, zuzycie)
    VALUES (p_id_mieszkania, p_id_uslugi, v_kwota, p_zuzycie);
    
    COMMIT;
    RETURN v_kwota;
END;
/

CREATE OR REPLACE TRIGGER trg_audit_czlonek
AFTER INSERT OR UPDATE OR DELETE ON czlonek
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO log_zmian_czlonka (id_czlonka, operacja, nowe_dane)
        VALUES (:NEW.id_czlonka, 'INSERT', :NEW.imie || ' ' || :NEW.nazwisko);
    ELSIF UPDATING THEN
        INSERT INTO log_zmian_czlonka (id_czlonka, operacja, stare_dane, nowe_dane)
        VALUES (:OLD.id_czlonka, 'UPDATE', :OLD.imie || ' ' || :OLD.nazwisko, :NEW.imie || ' ' || :NEW.nazwisko);
    ELSIF DELETING THEN
        INSERT INTO log_zmian_czlonka (id_czlonka, operacja, stare_dane)
        VALUES (:OLD.id_czlonka, 'DELETE', :OLD.imie || ' ' || :OLD.nazwisko);
    END IF;
END;
/

INSERT INTO uzytkownicy (login, haslo) VALUES ('admin', 'admin123');

INSERT INTO budynek (adres, liczba_pieter, rok_budowy, liczba_mieszkan) VALUES ('ul. Kwiatowa 15', 5, 2005, 20);
INSERT INTO budynek (adres, liczba_pieter, rok_budowy, liczba_mieszkan) VALUES ('ul. Słoneczna 8', 4, 2010, 16);
INSERT INTO budynek (adres, liczba_pieter, rok_budowy, liczba_mieszkan) VALUES ('ul. Parkowa 22', 6, 2015, 24);

INSERT INTO mieszkanie (id_budynku, numer, metraz, liczba_pokoi) VALUES (1, '1A', 45.5, 2);
INSERT INTO mieszkanie (id_budynku, numer, metraz, liczba_pokoi) VALUES (1, '2B', 65.0, 3);
INSERT INTO mieszkanie (id_budynku, numer, metraz, liczba_pokoi) VALUES (2, '3C', 55.0, 2);
INSERT INTO mieszkanie (id_budynku, numer, metraz, liczba_pokoi) VALUES (3, '4D', 80.0, 4);

INSERT INTO czlonek (id_mieszkania, imie, nazwisko, pesel, telefon, email) VALUES (1, 'Jan', 'Kowalski', '85010112345', '501123456', 'jan.kowalski@email.pl');
INSERT INTO czlonek (id_mieszkania, imie, nazwisko, pesel, telefon, email) VALUES (2, 'Anna', 'Nowak', '90020298765', '502234567', 'anna.nowak@email.pl');
INSERT INTO czlonek (id_mieszkania, imie, nazwisko, pesel, telefon, email) VALUES (3, 'Piotr', 'Wisniewski', '78030367890', '503345678', 'piotr.wisniewski@email.pl');
INSERT INTO czlonek (id_mieszkania, imie, nazwisko, pesel, telefon, email) VALUES (4, 'Maria', 'Dabrowska', '82040445678', '504456789', 'maria.dabrowska@email.pl');

INSERT INTO pracownik (imie, nazwisko, stanowisko, telefon, email) VALUES ('Tomasz', 'Maj', 'Konserwator', '600111222', 'tomasz.maj@spoldzielnia.pl');
INSERT INTO pracownik (imie, nazwisko, stanowisko, telefon, email) VALUES ('Ewa', 'Lewandowska', 'Administrator', '600222333', 'ewa.lewandowska@spoldzielnia.pl');

INSERT INTO uslugi (nazwa_uslugi, cena_za_jednostke, jednostka_miary) VALUES ('Woda zimna', 5.50, 'm3');
INSERT INTO uslugi (nazwa_uslugi, cena_za_jednostke, jednostka_miary) VALUES ('Woda ciepła', 12.80, 'm3');
INSERT INTO uslugi (nazwa_uslugi, cena_za_jednostke, jednostka_miary) VALUES ('Ogrzewanie', 4.20, 'm2');
INSERT INTO uslugi (nazwa_uslugi, cena_za_jednostke, jednostka_miary) VALUES ('Wywóz śmieci', 25.00, 'szt');
INSERT INTO uslugi (nazwa_uslugi, cena_za_jednostke, jednostka_miary) VALUES ('Czynsz', 8.50, 'm2');

INSERT INTO oplata (id_mieszkania, id_uslugi, kwota, zuzycie, status_oplaty) VALUES (1, 1, 55.00, 10, 'oplacone');
INSERT INTO oplata (id_mieszkania, id_uslugi, kwota, zuzycie, status_oplaty) VALUES (1, 3, 191.10, 45.5, 'nieoplacone');
INSERT INTO oplata (id_mieszkania, id_uslugi, kwota, zuzycie, status_oplaty) VALUES (2, 1, 66.00, 12, 'oplacone');
INSERT INTO oplata (id_mieszkania, id_uslugi, kwota, zuzycie, status_oplaty) VALUES (2, 5, 552.50, 65, 'nieoplacone');
INSERT INTO oplata (id_mieszkania, id_uslugi, kwota, zuzycie, status_oplaty) VALUES (3, 2, 128.00, 10, 'oplacone');
INSERT INTO oplata (id_mieszkania, id_uslugi, kwota, zuzycie, status_oplaty) VALUES (4, 4, 25.00, 1, 'nieoplacone');

INSERT INTO naprawa (id_mieszkania, id_pracownika, opis, status) VALUES (1, 1, 'Naprawa cieknącego kranu w łazience', 'wykonana');
INSERT INTO naprawa (id_mieszkania, id_pracownika, opis, status) VALUES (2, 1, 'Wymiana zamka w drzwiach wejściowych', 'w trakcie');
INSERT INTO naprawa (id_mieszkania, opis, status) VALUES (3, 'Awaria ogrzewania - brak ciepłej wody', 'zgloszona');

COMMIT;
